name: fastfold
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - pip:
      - biopython==1.79
      - dm-tree==0.1.6
      - ml-collections==0.1.0
      - PyYAML==5.4.1
      - requests==2.26.0
      - scipy==1.7.1
      - tqdm==4.62.2
      - typing-extensions==4.3.0
      - einops
      - ray==2.0.0
      - pyarrow
      - pandas
      - colossalai==0.2.7
  - pytorch::pytorch=1.12
  - pytorch::torchvision
  - pytorch::torchaudio
  - conda-forge::cudatoolkit=11.3
  - conda-forge::python=3.8
  - conda-forge::setuptools=59.5.0
  - conda-forge::pip
  - conda-forge::openmm=7.7.0
  - conda-forge::pdbfixer
  - bioconda::hmmer==3.3.2
  - bioconda::hhsuite==3.3.0
  - bioconda::kalign2==2.04
