name: Build

on: 
  pull_request:
    types: [synchronize, labeled]

jobs:
  build:
    name: Build and Test Colossal-AI
    if: |
        github.event.pull_request.draft == false &&
        github.base_ref == 'main' &&
        github.event.pull_request.base.repo.full_name == 'hpcaitech/FastFold' &&
        contains( github.event.pull_request.labels.*.name, 'Run Build and Test')
    runs-on: [self-hosted, gpu]
    container:
      image: hpcaitech/colossalai:0.1.9
      options: --gpus all --rm -v /data/scratch/fastfold:/data/scratch/fastfold
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v2
        with:
          repository: hpcaitech/FastFold
          ssh-key: ${{ secrets.SSH_KEY_FOR_CI }}
      - name: Install FastFold
        run: |
          cd FastFold
          [ ! -z "$(ls -A /github/home/cuda_ext_cache/)" ] && cp -r /github/home/cuda_ext_cache/* /__w/ColossalAI/ColossalAI/
          pip install -r requirements/requirements.txt
          pip install -v -e .
          cp -r /__w/ColossalAI/ColossalAI/build /github/home/cuda_ext_cache/
          cp /__w/ColossalAI/ColossalAI/*.so /github/home/cuda_ext_cache/
          pip install -r requirements/requirements-test.txt
      - name: Unit Testing
        run: |
          PYTHONPATH=$PWD pytest tests
        env:
          DATA: /data/scratch/cifar-10
          NCCL_SHM_DISABLE: 1
          LD_LIBRARY_PATH: /github/home/.tensornvme/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64