name: Build

on: 
  pull_request:
    types: [synchronize, labeled]

jobs:
  build:
    name: Build and Test FastFold
    if: |
        github.event.pull_request.draft == false &&
        github.base_ref == 'main' &&
        github.event.pull_request.base.repo.full_name == 'hpcaitech/FastFold' &&
        contains( github.event.pull_request.labels.*.name, 'Run Build and Test')
    runs-on: [self-hosted, gpu]
    container:
      image: hpcaitech/colossalai:0.1.10-torch1.11-cu11.3
      options: --gpus all --rm -v /data/scratch/fastfold:/data/scratch/fastfold
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v2
        with:
          repository: hpcaitech/FastFold
          ssh-key: ${{ secrets.SSH_KEY_FOR_CI }}
      - name: Install FastFold
        run: |
          [ ! -z "$(ls -A /github/home/fastfold_cache/)" ] && cp -r /github/home/fastfold_cache/* /__w/FastFold/FastFold/
          pip install pytorch==1.12 torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
          pip install colossalai==0.1.10+torch1.12cu11.3 -f https://release.colossalai.org
          pip install biopython==1.79 dm-tree==0.1.6 ml-collections==0.1.0 scipy==1.7.1 triton==2.0.0.dev20221003 pandas pytest
          pip install -e .
          cp -r /__w/FastFold/FastFold/build /github/home/fastfold_cache/
          cp /__w/FastFold/FastFold/*.so /github/home/fastfold_cache/
      - name: Unit Testing
        run: |
          PYTHONPATH=$PWD pytest tests/test_inference.py
        env:
          NCCL_SHM_DISABLE: 1


