name: Release bdist wheel

on:
  workflow_dispatch:
    inputs:
      torch_version:
        type: string
        description: torch version, separated by comma
        required: true
        default: "all"
      cuda_version:
        type: string
        description: cuda version, separated by comma
        required: true
      github_ref:
        type: string
        description: Branch or Tag
        default: 'main'
        required: true

jobs:
  build:
    name: Release bdist wheels
    if: github.repository == 'hpcaitech/FastFold' && contains(fromJson('["FrankLeeeee", "feifeibear", "Shenggan", "Gy-Lu"]'), github.actor)
    runs-on: [self-hosted, gpu]
    strategy:
      fail-fast: false
      matrix: ${{ "::set-output name=matrix::{\"container\":\"hpcaitech/cuda-conda:11.3\"}" }}
      image: ${{ matrix.container }}
      options: --gpus all --rm
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build bdist wheel
        run: |
          bash ./build_colossalai_wheel.sh pip https://download.pytorch.org/whl/cu113/torch-1.10.1%2Bcu113-cp39-cp39-linux_x86_64.whl torch-1.10.1+cu113-cp39-cp39-linux_x86_64.whl 11.3 3.9 1.10.1
        env:
          TORCH_VERSIONS: ${{ inputs.torch_version }}