name: Release bdist wheel

on:
  pull_request
jobs:
  matrix_preparation:
    name: Prepare Container List
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      env:
        TORCH_VERSIONS: 1.10.1
        CUDA_VERSIONS: 11.3
      run: |
        echo $TORCH_VERSIONS
        echo $CUDA_VERSIONS
        IFS=','
        DOCKER_IMAGE=()
        for cv in $CUDA_VERSIONS
        do
            DOCKER_IMAGE+=("\"hpcaitech/cuda-conda:${cv}\"")
        done
        container=$( IFS=',' ; echo "${DOCKER_IMAGE[*]}" )
        container="[${container}]"
        echo "$container"
        echo "::set-output name=matrix::{\"container\":$(echo "$container")}"
  build:
    name: Release bdist wheels
    needs: matrix_preparation
    if: github.repository == 'hpcaitech/FastFold' && contains(fromJson('["FrankLeeeee", "feifeibear", "Shenggan", "Gy-Lu"]'), github.actor)
    runs-on: [self-hosted, gpu]
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix_preparation.outputs.matrix)}}
    container:
      image: ${{ matrix.container }}
      options: --gpus all --rm
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Copy scripts and checkout
        run: |
          cp -r ./.github/workflows/* ./
          ln -s /github/home/pip_wheels ./pip_wheels
          git checkout $git_ref
        env:
          git_ref: workflow
      - name: Build bdist wheel
        run: |
          pip install beautifulsoup4 requests packaging
          python build_fastfold_wheel.py $TORCH_VERSIONS
        env:
          TORCH_VERSIONS: 1.10.1